version: "3"
services:
  tg_bot:
    image: tg_bot
    build:
      context: ./tg_bot
    environment:
      - TOKEN=${TOKEN}
      - RM_HOST=${RM_HOST}
      - RM_PORT=${RM_PORT}
      - RM_USER=${RM_USER}
      - RM_PASSWORD=${RM_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
    volumes:
      - pg_logs:/var/log/
    container_name: "tg_bot"
  db:
    image: db_image
    build:
      context: ./db_image
    volumes:
      - pg_logs:/var/log/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - DB_REPL_USER=${DB_REPL_USER}
      - DB_REPL_PASSWORD=${DB_REPL_PASSWORD}
      - DB_REPL_HOST=${DB_REPL_HOST}.mynet
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
    container_name: "${DB_HOST}"
  db_repl:
    image: db_repl_image
    build:
      context: ./db_repl_image
    container_name: "${DB_REPL_HOST}"
    environment:
      - DB_HOST=${DB_HOST}.mynet
      - DB_PORT=${DB_PORT}
      - DB_REPL_HOST=${DB_REPL_HOST}
      - DB_REPL_PORT=${DB_REPL_PORT}
      - DB_REPL_USER=${DB_REPL_USER}
      - POSTGRES_PASSWORD=${DB_REPL_PASSWORD}
volumes:
  pg_data:
  pg_logs:
networks:
  default:
    name: mynet