FROM postgres:15.8

RUN apt-get update && \
    apt-get install -y openssh-server && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV POSTGRES_PASSWORD=123

#RUN useradd -m golovanad && \
RUN  echo "postgres:123" | chpasswd

#RUN echo "postgres:123" | chpasswd

RUN usermod --shell /bin/bash postgres


COPY init.sql /docker-entrypoint-initdb.d/
COPY add_pg_hba.sh /docker-entrypoint-initdb.d/
#COPY log.sh /docker-entrypoint-initdb.d/

RUN chmod +x /docker-entrypoint-initdb.d/add_pg_hba.sh
#RUN chmod +x /docker-entrypoint-initdb.d/log.sh

#ENTRYPOINT ["docker-entrypoint.sh"]

#CMD ["postgres"]

RUN mkdir /var/run/sshd

#RUN mkdir -p /oracle/pg_data/archive && chmod 777 /oracle/pg_data/archive

RUN echo '#!/bin/bash\nservice ssh start && exec docker-entrypoint.sh postgres' > /start.sh

RUN chmod +x /start.sh

#RUN chmod -R 777 /var/lib/postgresql/data/log/*

CMD ["/start.sh"]

#RUN chmod -R 777 /var/lib/postgresql/data/log/*
