CREATE DATABASE tg_base;


CREATE USER repl_user REPLICATION LOGIN PASSWORD '123';


\c tg_base;

CREATE TABLE number (
    id SERIAL PRIMARY KEY,
    number VARCHAR(20) NOT NULL
);

CREATE TABLE email (
    id SERIAL PRIMARY KEY,
    email VARCHAR(100) NOT NULL
);

